# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Movix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'lottie-ios'
  pod 'CLTypingLabel'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'
  pod 'RxDataSources', '~> 5.0'
  pod "youtube-ios-player-helper"
  pod 'RealmSwift', '~>10'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'SwinjectStoryboard'
  pod 'ReachabilitySwift'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
